import = ["/home/shariq/.config/alacritty/themes/ayu-dark.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 24

[font.normal]
family = "JetBrainsMono Nerd Font"

[[keyboard.bindings]]
chars = """
\u0000~/.scripts/tmux-sessionizer
"""
key = "F"
mods = "Control"
